<?php $order = $this->getOrder();
$invoice = $order->getInvoiceCollection()->getLastItem();
$comment = $invoice->getCommentsCollection()->getFirstItem()->getComment();
$billing = $order->getBillingAddress();
$paymentBlock = Mage::helper('payment')->getInfoBlock($order->getPayment());
?>
<style>
    <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_STYLING);?>
</style>
<body style=" font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style=" font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
        <tr>
            <td align="center" valign="top" style="padding:20px 0 20px 0">
                <!-- [ header starts here] -->
                <table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
                    <!-- [ middle starts here] -->
                    <tr>
                        <td valign="top">
                            <p style="font-size:12px; line-height:16px; margin:0 0 10px 0;">
                                Your order # <?php echo $order->getIncrementId();?> has been <br/>
                                <strong><?php echo $order->getStatusLabel();?></strong>.
                            </p>
                            <p style="font-size:12px; line-height:16px; margin:0 0 10px 0;">You can check the status of your order by <a href="<?php echo $this->getBaseUrl();?>customer/account/"}}" style="color:#1E7EC8;">logging into your account</a>.</p>
                            <p style="font-size:12px; line-height:16px; margin:0 0 10px 0;"><?php echo $comment;?></p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>