<div class="content-header">
	<h3 class="icon-head head-newsletter-report"><?php echo $this->getTitle();?></h3>
</div>

<div class="connector-dashboard-block">
    <?php echo $this->getChildHtml('sales') ?>
</div>
<div class="connector-dashboard-block">
    <?php echo $this->getChildHtml('abandoned_cart') ?>
</div>
<div class="connector-dashboard-block">
    <?php echo $this->getChildHtml('customer') ?>
</div>
<div class="connector-dashboard-block">
    <?php echo $this->getChildHtml('subscriber') ?>
</div>
<div class="connector-dashboard-block-last">
    <?php echo $this->getChildHtml('rfm') ?>
</div>
