<div class="switcher">
	<label style="font-weight: bold" for="connector-log-selector">Select Log File:</label>
	<select id="connector-log-selector" style="width: 20em">
		<option value="connector">Marketing Automation Log</option>
        <?php if (Mage::helper('ddg')->getWebsiteConfig('dev/log/active')) : ?>
            <option value="system">Magento System Log</option>
            <option value="exception">Magento Exception Log</option>
        <?php endif; ?>
	</select>
    <button id="connector-log-reloader" style="margin-left: 5px;">
        <span>Reload</span>
    </button>
</div>
<div class="content-header">
	<h3 id="connector-log-header" class="icon-head head-newsletter-report">
		<?php echo $this->getTabTitle(); ?>
	</h3>
</div>

<div style="border: 4px solid #dfdfdf; overflow: hidden; height: 510px; padding: 5px;">
	<div id="log_data" style="width:100%;height:500px;overflow:auto;margin:0px;padding:3px;background:black;color:#2EC029;
	font:normal 11px Lucida Console, Courier New, serif;">
		<?php echo nl2br($this->escapeHtml(Mage::helper('ddg')->getLogFileContent())); ?>
	</div>
</div>

<script type="text/javascript">
	//<![CDATA[
	console_scroll();
	function console_scroll()
	{
		dh = $("log_data").scrollHeight
		ch = $("log_data").clientHeight
		if (dh > ch) {
			moveme = dh - ch
			$("log_data").scrollTop = moveme;
		}
	}

    //Observer select
    $('connector-log-selector').observe('change', function (event) {
        doUpdate($('connector-log-selector').getValue());
    });
    //Observe button click for reload
    $('connector-log-reloader').observe('click', function (event) {
        doUpdate($('connector-log-selector').getValue());
    });

	function doUpdate(log) {
		var url = '<?php echo Mage::helper('adminhtml')->getUrl(
			'adminhtml/connector/log'
		) ?>';
		new Ajax.Request(url,
			{
				method: 'post',
				parameters: {
					log: log
				},
				onSuccess: function (transport) {
					var json = transport.responseJSON;
					$('log_data').update(json.content);
					$('connector-log-header').update(json.header);
                    console_scroll();
				}
			});
	}
	//]]>
</script>