<div class="content-header">
    <h3 class="icon-head head-newsletter-report"><?php echo $this->getTabTitle(); ?></h3>
</div>

<div style="border: 4px solid #dfdfdf; overflow: scroll; height: 500px; padding: 5px;">
	<div id="log_data" style="width:100%;height:500px;overflow:auto;margin:0px;padding:3px;background:black;color:#2EC029;font:normal 11px Lucida Console, Courier New, serif;">
		<?php echo nl2br(Mage::helper('ddg')->getLogFileContent()); ?>
	</div>
</div>

<script type="text/javascript">
	//<![CDATA[
	console_scroll();
	function console_scroll()
	{
		dh = $("log_data").scrollHeight
		ch = $("log_data").clientHeight
		if (dh > ch) {
			moveme = dh - ch
			$("log_data").scrollTop = moveme;
		}
	}
	//]]>
</script>