<?php $items = $this->getBasketItems(); ?>
<?php if($items): ?>
    <?php $dynamicStyle = $this->getDynamicStyle(); ?>
    <style>
        .price-box p {
            margin: 0;
        }
        .product-name{
            color: <?php echo $dynamicStyle['nameColor'];?>;
            font-size: <?php echo $dynamicStyle['fontSize'];?>;
            <?php if (in_array('bold', $dynamicStyle['nameStyle'])) : ?>
                font-weight: bold;
            <?php endif; ?>
            <?php if (in_array('italic', $dynamicStyle['nameStyle'])) : ?>
                font-style: italic;
            <?php endif; ?>
            <?php if (in_array('underline', $dynamicStyle['nameStyle'])) : ?>
                text-decoration: underline;
            <?php endif; ?>
        }
        .product-price{
            color: <?php echo $dynamicStyle['priceColor'];?>;
            font-size: <?php echo $dynamicStyle['priceFontSize'];?>;
            <?php if (in_array('bold', $dynamicStyle['priceStyle'])) : ?>
                font-weight: bold;
            <?php endif; ?>
            <?php if (in_array('italic', $dynamicStyle['priceStyle'])) : ?>
                font-style: italic;
            <?php endif; ?>
            <?php if (in_array('underline', $dynamicStyle['priceStyle'])) : ?>
                text-decoration: underline;
            <?php endif; ?>
        }
        .product-url{
            color: <?php echo $dynamicStyle['urlColor'];?>;
            font-size: <?php echo $dynamicStyle['urlFontSize'];?>;

            <?php if (in_array('bold', $dynamicStyle['linkStyle'])) : ?>
                font-weight: bold;
            <?php endif; ?>
            <?php if (in_array('italic', $dynamicStyle['linkStyle'])) : ?>
                font-style: italic;
            <?php endif; ?>
            <?php if (in_array('underline', $dynamicStyle['linkStyle'])) : ?>
                text-decoration: underline;
            <?php endif; ?>
        }
        .other-text{
            color: <?php echo $dynamicStyle['otherColor'];?>;
            font-size: <?php echo $dynamicStyle['otherFontSize'];?>;
            <?php if (in_array('bold', $dynamicStyle['otherStyle'])) : ?>
                font-weight: bold;
            <?php endif; ?>
            <?php if (in_array('italic', $dynamicStyle['otherStyle'])) : ?>
                font-style: italic;
            <?php endif; ?>
            <?php if (in_array('underline', $dynamicStyle['otherStyle'])) : ?>
                text-decoration: underline;
            <?php endif; ?>
        }
        .product-table{
            font-family: <?php echo $dynamicStyle['docFont'];?>;
            background-color: <?php echo $dynamicStyle['docBackgroundColor'];?>;
            width: 100% !important;
        }
        .product-table img{
            display: block;
            margin-left: auto;
            margin-right: auto
        }
        .product-table td{
            width: 25%;
            padding-bottom: 10px;
            text-align: center;
        }
        tr.noborder td {
            border: none!important;
        }

        <?php echo $dynamicStyle['dynamicStyling'];?>
        /** Responsive  **/
        @media (max-width: 760px) {
            /* Force table to not be like tables anymore */
            .product-table table, .product-table thead, .product-table tbody,
            .product-table th, .product-table td, .product-table tr {
                display: block;
            }

            .product-table td {
                width: 200px !important;
            }

            .product-table {
                width: auto !important;
                margin: 0 auto;
                float: none!important;
            }

            .product-table tr {
                border: none;
                border-bottom: 1px solid #eee;
                margin-bottom: 10px !important;
            }

            .product-table td {
                border: none !important;
                position: relative;
            }

            .quantity:before {
                content: 'Quantity:';
            }

            .product-table td:before {
                position: relative;
            }

            .product-table tr th {
                display: none !important;
                border: none !important;
            }
            .hidemob {
                display: none!important;
            }

        }
    </style>
    <table class="product-table" style ='float:left; width:600px; border: 1px solid #cbd3d4; border-collapse: collapse; padding: 5px;'>
        <tr>
            <th class="other-text" style="padding: 5px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Image");?></th>
            <th class="other-text" style="padding: 5px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Description");?></th>
            <th class="other-text" style="padding: 5px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Quantity");?></th>
            <th class="other-text" style="padding: 5px; border-bottom: 1px solid #cbd3d4;">Total</th>
        </tr>
        <?php foreach($items as $item):?>
            <tr>
                <td style="padding: 5px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;">
                    <img alt="<?php echo $this->stripTags($this->getImageLabel($item['product'], 'small_image'), null, true) ?>"
                         src="<?php echo $this->getProductImage($_product); ?>" width="85" height="85" align="middle"
                         border="0">
                </td>
                <td  class="product-name" style="padding: 1px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;">
                    <a class="product-url" href="<?php echo $item['productUrl'];?>"><?php echo
                        $this->escapeHtml($item['product']->getName())  . '</a></br>' . $item['inStock'];?></td>
                <td class="product-price quantity" style="padding: 1px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php
                    echo (int)$item['qty'];?></td>
                <td class="product-price" style="padding: 5px; border-bottom: 1px solid #cbd3d4;"><?php echo $item['total'];?></td>
            </tr>
        <?php endforeach;?>
        <tr style="border: none!important;">
            <td class="hidemob" style="border: none;"></td>
            <td class="hidemob" style="border: none;"></td>
            <td class="hidemob" style="border: none;"></td>
            <td class="other-text" style="padding: 5px;">
                <?php echo 'Order Total: ' . $item['grandTotal'];?>
            </td>
        </tr>
    </table>
    <?php

    if ($this->canShowUrl()) : ?>
        <p style="text-align: center">
            <a href="<?php echo $this->getUrlForLink(); ?>" class="product-url">
                <strong>
                    <?php
                    $link = ($this->takeMeToCartTextForUrl())? $this->__($this->takeMeToCartTextForUrl()) : $this->__('Take Me To My Basket');
                    echo $link;?>
                </strong>
            </a>
    <?php endif; ?>
<?php endif;