<?php
$items = $this->getBasketItems();
$helper = Mage::helper('core');
?>
<?php if($items): ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html">
    <head><title>Basket</title></head>
    <body">
    <?php
        $dynamicStyle = $this->getDynamicStyle();
    ?>
    <style>
        .product-name{
            color: <?php echo $dynamicStyle['nameColor'];?>;
            font-size: <?php echo $dynamicStyle['fontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['nameStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['nameStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['nameStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-price{
            color: <?php echo $dynamicStyle['priceColor'];?>;
            font-size: <?php echo $dynamicStyle['priceFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['priceStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['priceStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['priceStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .proudct-url{
            color: <?php echo $dynamicStyle['urlColor'];?>;
            font-size: <?php echo $dynamicStyle['urlFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['linkStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['linkStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['linkStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .other-text{
            color: <?php echo $dynamicStyle['otherColor'];?>;
            font-size: <?php echo $dynamicStyle['otherFontSize'];?>;
        <?php if(in_array('bold', $dynamicStyle['otherStyle'])): ?>
            font-weight: bold;
        <?php endif; ?>
        <?php if(in_array('italic', $dynamicStyle['otherStyle'])): ?>
            font-style: italic;
        <?php endif; ?>
        <?php if(in_array('underline', $dynamicStyle['otherStyle'])): ?>
            text-decoration: underline;
        <?php endif; ?>
        }
        .product-table{
            font-family: <?php echo $dynamicStyle['docFont'];?>;
            background-color: <?php echo $dynamicStyle['docBackgroundColor'];?>;
            width: 100% !important;
        }
        .product-table img{
            display: block;
            margin-left: auto;
            margin-right: auto
        }
        .product-table td{
            width: 25%;
            padding-bottom: 10px;
        }
        <?php echo $dynamicStyle['dynamicStyling'];?>
        /** Responsive  **/
        @media (max-width: 760px) {
            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr {
                display: block;
            }
            .product-table td{
                width: 200px !important;
            }
            .product-table{
                width: auto !important;
            }
            tr {
                border: none;
                border-bottom: 1px solid #eee;
                margin-bottom: 10px !important;
            }
            td {
                border: none !important;
                position: relative;
            }
            td:before {
                position: relative;
            }
            tr th {
                display: none !important;
                border: none !important;
            }
            /** Does not work in email clients
            td:nth-of-type(1):before { content: ""; }
            td:nth-of-type(2):before { content: ""; }
            td:nth-of-type(3):before { content: "Quantity: ";}
            td:nth-of-type(4):before { content: "Total: "; }
            tr:last-child td:nth-of-type(1):before { content: ""; }
            tr:last-child td:nth-of-type(2):before { content: ""; }
            tr:last-child td:nth-of-type(3):before { content: ""; }
            tr:last-child td:nth-of-type(4):before { content: ""; }
            td:before { font-weight: bold; }**/
        }
    </style>
    <table style ='float:left; width:600px; border: 1px solid #cbd3d4; border-collapse: collapse; padding: 5px;' class="product-table">
        <tr>
            <th class="other-text" style="border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Image");?></th>
            <th class="other-text" style="border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Description");?></th>
            <th class="other-text" style="border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo $this->__("Quantity");?></th>
            <th class="other-text" style="border-bottom: 1px solid #cbd3d4;">Total</th>
        </tr>

        <?php foreach($items as $one):?>
            <?php
            if($one->getParentItemId() != null)
                continue;
            $_product = Mage::getModel('catalog/product')->load($one->getProductId());

            $inStock = ($_product->getStockItem()->getIsInStock())? 'In Stock' : 'Out of stock';
            $total = $helper->currency($one->getBaseRowTotalInclTax());
            $productUrl = $_product->getProductUrl();
            $grandTotal = $helper->currency($this->getGrandTotal());
            ?>
            <tr>
                <td style="padding: 1px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;">
                    <img alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
	                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85);?>" width="85" height="85" align="middle" border="0">
                </td>
                <td  class="product-name" style="padding: 1px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;">
	                Product Name : <a class="proudct-url" href="<?php echo $productUrl;?>"><?php echo  $_product->getName()  . '</a></br>'. $inStock;?></td>
                <td class="product-price" style="padding: 1px; border-bottom: 1px solid #cbd3d4; border-right: 1px solid #cbd3d4;"><?php echo (int)$one->getQty();?></td>
                <td class="product-price" style="padding: 1px; border-bottom: 1px solid #cbd3d4;"><?php echo $total;?></td>
            </tr>

        <?php endforeach;?>
        <tr>
            <td style="padding: 1px; border-right: 1px solid #cbd3d4; border-bottom: 1px solid #cbd3d4;"></td>
            <td style="padding: 1px; border-right: 1px solid #cbd3d4; border-bottom: 1px solid #cbd3d4;"></td>

            <td class="other-text" style="padding: 1px; border-right: 1px solid #cbd3d4; border-bottom: 1px solid #cbd3d4;">Order Total</td>
            <td class="other-text" style="padding: 1px; border-bottom: 1px solid #cbd3d4;">
                <?php echo $grandTotal;?>
            </td>
        </tr>
        <?php if($this->canShowUrl()): ?>
            <tr>
                <td class="other-text" style="padding: 1px;"></td>
                <td class="other-text" style="padding: 1px;"></td>
                <td class="other-text" style="padding: 1px;"></td>
                <td class="other-text" style="padding: 1px;">
                    <div align="center" style="padding: 5px;">
                        <a href="<?php echo $this->getUrlForLink(); ?>" class="proudct-url">
                            <strong>
                                <?php
                                    if($text = $this->takeMeToCartTextForUrl())
                                        echo $this->__($text);
                                    else
                                        echo $this->__('Take Me To My Basket');
                                ?>
                            </strong>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endif; ?>
    </table>
    </body>
    </html>
<?php endif;