<?php $coupon = $this->generateCoupon(); ?>
<?php if($coupon): ?>
    <?php
        $style = explode(',', Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_COUPON_STYLE));
    ?>
    <style>
        .edc-coupon{
            color: <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_COUPON_COLOR);?>;
            font-size: <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_COUPON_FONT_SIZE);?>;
            <?php if(in_array('bold', $name_style)): ?>
                font-weight: bold;
            <?php endif; ?>
            <?php if(in_array('italic', $name_style)): ?>
                font-style: italic;
            <?php endif; ?>
            <?php if(in_array('underline', $name_style)): ?>
                text-decoration: underline;
            <?php endif; ?>
            font-family: <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_COUPON_FONT);?>;
            background-color: <?php echo Mage::getStoreConfig(Dotdigitalgroup_Email_Helper_Config::XML_PATH_CONNECTOR_DYNAMIC_COUPON_BG_COLOR);?>;
        }
    </style>
    <div class="edc-coupon">
        <?php echo $coupon; ?>
    </div>
<?php endif; ?>

