<?php if(Mage::helper('ddg')->getRoiTrackingEnabled()):
    $order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
    $orderId = $this->getOrderId();
    $items = $order->getAllItems();
    $total = number_format($order->getBaseGrandTotal(), 2, '.', ',');
?>
<script type="text/javascript">
    document.observe('dom:loaded', function() {
        <?php foreach ($items as $item):?>
        <?php if($item->getParentItemId() != null) continue;?>
_dmTrack("product", "<?php echo str_replace('"', ' ',  $item->getName())?>");
        <?php endforeach;?>
_dmTrack("CheckOutAmount", "<?php echo $total;?>");
    });
</script>
<?php endif;
