<?php
if(Mage::helper('ddg')->isPageTrackingAvailable()) :?>
    <script type="text/javascript">
        var dmTracks = window.dmTracks || [];
        (function() {
            var regionPrefix = "<?= Mage::helper('ddg')->getRegionPrefix() ?>";
            var connector = document.createElement('script');
            connector.type = 'text/javascript';
            connector.async = true;
            connector.src = '//' + regionPrefix + 't.trackedlink.net/_dmmpt.js';
            connector.addEventListener('load', function (e) {
                for (var d = 0; d < dmTracks.length; d++) {
                    _dmTrack(dmTracks[d].name, dmTracks[d].value);
                }
                _dmCallHandler();
            });
            document.body.appendChild(connector);
        })();
    </script>
<?php endif;
