<?php
if(Mage::helper('ddg')->isPageTrackingAvailable()) :?>
    <script type="text/javascript">
        (function(){
            var regionPrefix = "<?php echo Mage::helper('ddg')->getRegionPrefix(); ?>";
            var connector = document.createElement('script');
            connector.type = 'text/javascript';
            connector.src = '//' + regionPrefix + 't.trackedlink.net/_dmpt.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(connector, s);
        })();
    </script>
<?php endif;
