<script type="text/javascript">
	/* <![CDATA[ */
	(function() {
		var domain = "<?php echo $this->getDomain();?>";
		var apiusername = "<?php echo $this->getApiUsername();?>";
		var mageVersion = "<?php echo $this->getMageVersion();?>";
		var connectorVersion = "<?php echo $this->getConnectorVersion();?>";
		var features = encodeURIComponent('<?php echo $this->getFeatures();?>');
		var cronInstalled = "<?php echo $this->getCronInstalled();?>";
		var websitesnames = encodeURIComponent('<?php echo $this->getWebsiteNames();?>');
		var email = "<?php echo $this->getAccountEmail();?>";

		var dmProtocol;
		if (window.location.protocol.toLowerCase() == 'https:') {
			dmProtocol = 'https:';
		} else {
			dmProtocol = 'http:';
		}
		var dmUrl = dmProtocol + "//integration.dotmailerformagento.co.uk/install/?domain=" + domain + "&apiusername=" + apiusername + "&mage=" + mageVersion +
				"&email=" + email + "&connector=" + connectorVersion +"&features=" + features + "&cron=" + cronInstalled + "&websitenames=" + websitesnames;

		document.write('<scr' + 'ipt type="text/javascript" src="' + dmUrl + '"></scr' + 'ipt>');
	})();
	/* ]]> */
</script>



