<div id="ddg-edc-preview">
    <div style="width: 200px; height: auto; float: right">
        <div align="center" style="font-weight: bold; padding: 3px; font-size: 12px;">
            PRODUCT STYLING PREVIEW
        </div>
        <div id="connector_configuration_dynamic_content_style_doc-preview"
             style="width: 200px; height: auto; border: solid 1px black; padding-top: 50px; padding-bottom: 50px;">
            <a href="<?php echo Mage::getBaseUrl(); ?>" target="_blank" title="Sample Image">
                <img src="<?php echo Mage::getDesign()->getSkinUrl('images/catalog/product/placeholder/image.jpg',
                    array('_area' => 'frontend')); ?>"
                     width="85" height="85" alt="Sample Image"
                     style="display: block; margin-left: auto; margin-right: auto; "/>
            </a>
            <div id="connector_configuration_dynamic_content_style_name-preview" align="center">
                Product Name
            </div>
            <div id="connector_configuration_dynamic_content_style_price-preview" align="center">
                <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . "99.99"; ?>
            </div>
            <div align="center">
                <a id="connector_configuration_dynamic_content_style_link-preview" target="_blank"
                   href="<?php echo Mage::getBaseUrl(); ?>">View Now</a>
            </div>
        </div>
        <div align="center" style="margin-top: 20px; font-weight: bold; padding: 3px; font-size: 12px;">
            COUPON STYLING PREVIEW
        </div>
        <div id="connector_configuration_dynamic_content_style_coupon-preview" align="center"
             style="width: 200px; height: auto; border: solid 1px black; padding-top: 10px; padding-bottom: 10px;">
            DOT-XXX-XXX-XXX
        </div>
    </div>
</div>

<script type="text/javascript">
    var $j = jQuery.noConflict();
    $j(document).ready(function () {

        var s = $j("#ddg-edc-preview");
        var pos = s.position();
        $j(window).scroll(function () {
            var windowpos = $j(window).scrollTop();
            if (windowpos >= pos.top &&
                windowpos < ($j("#connector_configuration_dynamic_content_style_coupon_style").position().top - 350)) {
                s.attr("style", ""); //kill absolute positioning
                s.css({position: "fixed", top: "80px", left: $j(document).innerWidth() - 250});
            } else if (windowpos
                >= ($j("#connector_configuration_dynamic_content_style_coupon_style").position().top - 350)) {
                s.css({
                    position: "absolute",
                    top: ($j("#connector_configuration_dynamic_content_style_coupon_style").position().top - 350) + "px",
                    left: $j(document).innerWidth() - 250
                });
            } else {
                s.css({
                    position: "absolute",
                    top: pos.top + "px",
                    left: $j(document).innerWidth() - 250
                });
            }
        });

        $j(window).resize(function () {
            $j("#ddg-edc-preview").css({left: $j(document).innerWidth() - 250});
        });
        var elementsA = [
            $j("#connector_configuration_dynamic_content_style_link_text"),
            $j("#connector_configuration_dynamic_content_style_name_color"),
            $j("#connector_configuration_dynamic_content_style_name_font_size"),
            $j("#connector_configuration_dynamic_content_style_price_color"),
            $j("#connector_configuration_dynamic_content_style_price_font_size"),
            $j("#connector_configuration_dynamic_content_style_link_color"),
            $j("#connector_configuration_dynamic_content_style_link_font_size"),
            $j("#connector_configuration_dynamic_content_style_font_picker"),
            $j("#connector_configuration_dynamic_content_style_doc_color"),
            $j("#connector_configuration_dynamic_content_style_coupon_color"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_size"),
            $j("#connector_configuration_dynamic_content_style_coupon_font_picker"),
            $j("#connector_configuration_dynamic_content_style_coupon_doc_color")
        ];
        var elementsB = [
            $j("#connector_configuration_dynamic_content_style_name_style"),
            $j("#connector_configuration_dynamic_content_style_price_style"),
            $j("#connector_configuration_dynamic_content_style_link_style"),
            $j("#connector_configuration_dynamic_content_style_coupon_style")
        ];
        $j.each(elementsA, function (index, element) {
            var id = element.attr("id");
            var value = element.val();
            doYourThing(id, value);
            $(element).on("change keyup blur input", function () {
                id = element.attr("id");
                value = element.val();
                doYourThing(id, value);
            });
        });
        $j.each(elementsB, function (index, element) {
            var id = element.attr("id");
            var value = element.val();
            doYourThing(id, value);
            $(element).on("change", function () {
                id = element.attr("id");
                value = element.val();
                doYourThing(id, value);
            });
        });

        function doYourThing(id, value) {
            var link = $j("#" + "connector_configuration_dynamic_content_style_link-preview");
            var name = $j("#" + "connector_configuration_dynamic_content_style_name-preview");
            var doc = $j("#" + "connector_configuration_dynamic_content_style_doc-preview");
            var price = $j("#" + "connector_configuration_dynamic_content_style_price-preview");
            var coupon = $j("#" + "connector_configuration_dynamic_content_style_coupon-preview");
            switch (id) {
                case "connector_configuration_dynamic_content_style_link_text":
                    if (value == "") {
                        value = "View Now";
                    }
                    link.text(value);
                    break;
                case "connector_configuration_dynamic_content_style_name_color":
                    name.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_name_font_size":
                    name.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_name_style":
                    applyStyle(value, name);
                    break;
                case "connector_configuration_dynamic_content_style_price_color":
                    price.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_price_font_size":
                    price.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_price_style":
                    applyStyle(value, price);
                    break;
                case "connector_configuration_dynamic_content_style_link_color":
                    link.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_link_font_size":
                    link.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_link_style":
                    applyStyle(value, link);
                    break;
                case "connector_configuration_dynamic_content_style_font_picker":
                    doc.css("font-family", value);
                    break;
                case "connector_configuration_dynamic_content_style_doc_color":
                    doc.css("background-color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_color":
                    coupon.css("color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_size":
                    coupon.css("font-size", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_font_picker":
                    coupon.css("font-family", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_doc_color":
                    coupon.css("background-color", value);
                    break;
                case "connector_configuration_dynamic_content_style_coupon_style":
                    applyStyle(value, coupon);
                    break;
            }
        }

        function applyStyle(styles, element) {
            element.css({"font-weight": "normal", "font-style": "normal", "text-decoration": "none"});
            $j.each(styles, function (index, style) {
                switch (style) {
                    case "nostyle":
                        element.css({"font-weight": "normal", "font-style": "normal", "text-decoration": "none"});
                        return false;
                        break;
                    case "bold":
                        element.css("font-weight", "bold");
                        break;
                    case "italic":
                        element.css("font-style", "italic");
                        break;
                    case "underline":
                        element.css("text-decoration", "underline");
                        break;
                }
            });
        }
    });
</script>